// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz26o6i0ZDCUVfAEmCS7S3UIuev1MxWXY',
    appId: '1:871941574415:web:8f5900166853f1fd95387a',
    messagingSenderId: '871941574415',
    projectId: 'doc2heal-doctor',
    authDomain: 'doc2heal-doctor.firebaseapp.com',
    storageBucket: 'doc2heal-doctor.appspot.com',
    measurementId: 'G-GXLL3D18KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGZ_irCEw2qamHUEyki4YWjucIXwtEPF4',
    appId: '1:871941574415:android:d00a3459e99ffba295387a',
    messagingSenderId: '871941574415',
    projectId: 'doc2heal-doctor',
    storageBucket: 'doc2heal-doctor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCmXuMTbQpQ63PdKgXbC9HQfN0VvXog0w',
    appId: '1:871941574415:ios:40b5f6c1ba64c14595387a',
    messagingSenderId: '871941574415',
    projectId: 'doc2heal-doctor',
    storageBucket: 'doc2heal-doctor.appspot.com',
    iosBundleId: 'com.example.doc2healDoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCmXuMTbQpQ63PdKgXbC9HQfN0VvXog0w',
    appId: '1:871941574415:ios:202afaca44b223a595387a',
    messagingSenderId: '871941574415',
    projectId: 'doc2heal-doctor',
    storageBucket: 'doc2heal-doctor.appspot.com',
    iosBundleId: 'com.example.doc2healDoctor.RunnerTests',
  );
}
